# Discussion 2

In [213]:
print( "The first element is {} and the second element is {}.".format([1,2,3], 2.2) )

The first element is [1, 2, 3] and the second element is 2.2.


In [166]:
print( "The second element is {1} and the first element is {0}.".format(1, 2) )

The second element is 2 and the first element is 1.


In [216]:
def is_type_int(L):
    if len(L)==0:
        print('None')
        return None
    else:
        return [isinstance(x,int) for x in L]  

In [218]:
L=[1,2,3]
[isinstance(x,int) for x in L]

[True, True, True]

In [219]:

result=[]
for x in L:
    result.append(isinstance(x,int))

print(result)

[True, True, True]


In [171]:
is_type_int([1,2,3,4])

[True, True, True, True]

In [172]:
is_type_int([1,2,'a',4])

[True, True, False, True]

In [217]:
is_type_int([])

None


In [220]:
is_type_int()

TypeError: is_type_int() missing 1 required positional argument: 'L'

In [229]:
def is_type_int(L=None):
    if L==None:
        print("None Input")
        return None
    else:
        return [isinstance(x,int) for x in L] 

In [231]:
L=is_type_int()
L

None Input
None


In [144]:
 [isinstance(x,int) for x in [] ] 

[]

### Immutable Objects

In [223]:
a='asd'
#a=[1,2,3]
#a=(1,2,3)

In [225]:
a[0]="A"

TypeError: 'str' object does not support item assignment

The code in the except block will only be executed if raise an exception.

In [226]:
try: 
    a[0]='A'
    print("finish")
except TypeError:
    print("The type of input is wrong!")

print(a)

The type of input is wrong!
asd


In [185]:
b='asd'
b.replace("a","A")

'Asd'

## for Loops

In [232]:
L=[1,2,3,4]

In [233]:
for x in L:
    print(x+1)        # don't forget indenation

2
3
4
5


In [188]:
for i in range(len(L)):   # i in [0,1,2,3]
    print( L[i]+1 )

2
3
4
5


### range( ) function

In [234]:
for i in range(5):         # values from 0 to 4
    print(i)

0
1
2
3
4


In [190]:
for i in range(5,10):      # values from 5 to 9
    print(i)

5
6
7
8
9


In [191]:
for i in range(5,10,2):    # increment the sequence with 2
    print(i)

5
7
9


You may want to create a new variable to record your iteration result.

In [235]:
L=[1,2,3,4,5,6,7,8,9]

In [236]:
count=0
for x in L:
    if x > 5:
        count+=1

print(count)

4


In [237]:
result=[]
for x in L:
    result.append( type(x) )

result

[int, int, int, int, int, int, int, int, int]

### break and continue 

With the break statement we can stop the loop before it has looped through all the items:

In [198]:
l=[2,4,7,9,5,2,1]
for x in l:
    if x > 6:
        print("We find an element larger than 6")
        break
print(x)

We find an element larger than 6
7


With the continue statement we can stop the current iteration of the loop, and continue with the next:

In [238]:
l=[2,4,7,9,5,2,1]
for x in l:
    if x > 6:
        print("We find an element larger than 6")
        continue
        print("continue")
print(x)

We find an element larger than 6
We find an element larger than 6
1


In [241]:
for x in range(5):
    if x >2:
        pass
        print(x)
    #print(x)

3
4


### Nested loops

In [244]:
M=[[1,2,3],[4,5,6],[7,8,9]]

for i in range(len(M)):
    for j in range(len(M[0])):
        if M[i][j]==5:
            M[i][j]*=10
        else:
            M[i][j]+=1

print(M)

[[2, 3, 4], [5, 50, 7], [8, 9, 10]]


In [245]:
M=[[1,2,3],[4,5,6],[7,8,9]]
M[0]

[1, 2, 3]

The else keyword in a for loop specifies a block of code to be executed when the loop is finished:

In [57]:
for x in range(6):
    print(x)
else:
    print("Finally finished!")

0
1
2
3
4
5
Finally finished!


## while loops

A while loop specifies a condition and a block of code that is to be executed until the condition evaluates to False or the loop is ended with break

In [208]:
x=10
addup=0
while x>0:
    print(addup)
    addup+=x
    x-=1
    
print("The toal sum is: ",addup)

0
10
19
27
34
40
45
49
52
54
The toal sum is:  55


In [209]:
i = 1
while i < 6:
    print(i)
    if i == 3:
        break
    i += 1

1
2
3


In [246]:
i = 0
while i < 6:
    i += 1 
    if i == 3:
        continue
    print(i)

1
2
4
5
6


## import

A model is simply a file with the ".py" entension containing Python code. If we want to aceess the variables and functions defined in "model_name.py", we could use import funciotn.

In [79]:
import numpy

In [80]:
numpy.pi

3.141592653589793

In [81]:
import numpy as np

In [82]:
np.pi

3.141592653589793

## Some Numpy Arrays

In [94]:
np.array?

In [89]:
a = np.array([1, 2, 3])
print(a)               
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


The elements of Numpy Array must have the same data type. It's different with List !

In [116]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [211]:
np.array([1,2.5,3])

array([1. , 2.5, 3. ])

In [91]:
A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [92]:
A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)

[[1.1 2.  3. ]
 [3.  4.  5. ]]


In [93]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


### shape and reshape

In [115]:
a = np.array([1, 2, 3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [117]:
b=a.reshape(2,2)
print(b)

[[1 2]
 [3 4]]


In [113]:
b=a.reshape(4,1)
print(b)

[[1]
 [2]
 [3]
 [4]]


In [114]:
b=a.reshape(1,4)
print(b)

[[1 2 3 4]]


### arange and linspace

arange is similar to the built-in range( ) function

In [121]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [123]:
# Starting at 0, ending at 10, stepping by 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [124]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])